/*
 * m_num.c
 *
 * Created: 11/19/2013 1:28:28 AM
 *  Author: Sean
 */ 

#define F_CPU 16000000UL

#include <avr/io.h>
#include "m_general.h"
#include "m_port.h"

#define LOWERLEFT1 PORTG
#define LOWERLEFT2 5
#define MIDDLE1 PORTG
#define MIDDLE2 3
#define LOWERRIGHT1 PORTG
#define LOWERRIGHT2 6
#define BOTTOM1 PORTG
#define BOTTOM2 4
#define UPPERLEFT1 PORTG
#define UPPERLEFT2 2
#define TOP1 PORTG
#define TOP2 1
#define UPPERRIGHT1 PORTG
#define UPPERRIGHT2 0

void disp(int num) {
	switch (num) {
		case 1:
			set(LOWERRIGHT1,LOWERRIGHT2);
			set(UPPERRIGHT1,UPPERRIGHT2);
			clear(TOP1,TOP2);
			clear(UPPERLEFT1,UPPERLEFT2);
			clear(LOWERLEFT1,LOWERLEFT2);
			clear(BOTTOM1,BOTTOM2);
			clear(MIDDLE1,MIDDLE2);
			break;
		case 2:
			clear(LOWERRIGHT1,LOWERRIGHT2);
			set(UPPERRIGHT1,UPPERRIGHT2);
			set(TOP1,TOP2);
			clear(UPPERLEFT1,UPPERLEFT2);
			set(LOWERLEFT1,LOWERLEFT2);
			set(BOTTOM1,BOTTOM2);
			set(MIDDLE1,MIDDLE2);
			break;
		case 3:
			set(LOWERRIGHT1,LOWERRIGHT2);
			set(UPPERRIGHT1,UPPERRIGHT2);
			set(TOP1,TOP2);
			clear(UPPERLEFT1,UPPERLEFT2);
			clear(LOWERLEFT1,LOWERLEFT2);
			set(BOTTOM1,BOTTOM2);
			set(MIDDLE1,MIDDLE2);
			break;
		case 4:
			set(LOWERRIGHT1,LOWERRIGHT2);
			set(UPPERRIGHT1,UPPERRIGHT2);
			clear(TOP1,TOP2);
			set(UPPERLEFT1,UPPERLEFT2);
			clear(LOWERLEFT1,LOWERLEFT2);
			clear(BOTTOM1,BOTTOM2);
			set(MIDDLE1,MIDDLE2);
			break;
		case 5:
			set(LOWERRIGHT1,LOWERRIGHT2);
			clear(UPPERRIGHT1,UPPERRIGHT2);
			set(TOP1,TOP2);
			set(UPPERLEFT1,UPPERLEFT2);
			clear(LOWERLEFT1,LOWERLEFT2);
			set(BOTTOM1,BOTTOM2);
			set(MIDDLE1,MIDDLE2);
		break;
		case 6:
			set(LOWERRIGHT1,LOWERRIGHT2);
			clear(UPPERRIGHT1,UPPERRIGHT2);
			set(TOP1,TOP2);
			set(UPPERLEFT1,UPPERLEFT2);
			set(LOWERLEFT1,LOWERLEFT2);
			set(BOTTOM1,BOTTOM2);
			set(MIDDLE1,MIDDLE2);
			break;
		case 7:
			set(LOWERRIGHT1,LOWERRIGHT2);
			set(UPPERRIGHT1,UPPERRIGHT2);
			set(TOP1,TOP2);
			clear(UPPERLEFT1,UPPERLEFT2);
			clear(LOWERLEFT1,LOWERLEFT2);
			clear(BOTTOM1,BOTTOM2);
			clear(MIDDLE1,MIDDLE2);
			break;
		case 8:
			set(LOWERRIGHT1,LOWERRIGHT2);
			set(UPPERRIGHT1,UPPERRIGHT2);
			set(TOP1,TOP2);
			set(UPPERLEFT1,UPPERLEFT2);
			set(LOWERLEFT1,LOWERLEFT2);
			set(BOTTOM1,BOTTOM2);
			set(MIDDLE1,MIDDLE2);
			break;
		case 9:
			set(LOWERRIGHT1,LOWERRIGHT2);
			set(UPPERRIGHT1,UPPERRIGHT2);
			set(TOP1,TOP2);
			set(UPPERLEFT1,UPPERLEFT2);
			clear(LOWERLEFT1,LOWERLEFT2);
			set(BOTTOM1,BOTTOM2);
			set(MIDDLE1,MIDDLE2);
			break;
		case 0:
			set(LOWERRIGHT1,LOWERRIGHT2);
			set(UPPERRIGHT1,UPPERRIGHT2);
			set(TOP1,TOP2);
			set(UPPERLEFT1,UPPERLEFT2);
			set(LOWERLEFT1,LOWERLEFT2);
			set(BOTTOM1,BOTTOM2);
			clear(MIDDLE1,MIDDLE2);
			break;
	}
}

void m_num_init() {
	set(DDRG,0);
	set(DDRG,1);
	set(DDRG,2);
	set(DDRG,3);
	set(DDRG,4);
	set(DDRG,5);
	set(DDRG,6);
}